### DISCUSSION TITLE
Installation on Synology

### DISCUSSION THREAD

**Discussion by AbDhops** [dcmartin/motion-ai#10] [Q&A]
Hi All,
After looking lot of wonderfull possibilities, I decided to bite the bullet and start installing motion-ai on synology.
I already have plenty of docker containers running, including separate container for HomeAssistant Core (as described [here](https://www.home-assistant.io/docs/installation/docker/)), Mosquitto MQTT, Node Red, deconz, volkszaehler etc. I like the way that all are working seprately and communicating each other to form big system. Now, with motion-ai, my idea was to expand the system to make it also working in one container and using existing resources Mosquitto or Home Assistant. Once entire system is up and running, I planned to optimize the scripts or docker compose.

If I understood installation process correctly, complete installation process described here is applicable for Raspberry PI. So I created docker container to run official "ubuntu" image. Here is my docker compose file.
```
version: "3"

services:
  ubuntu:
    container_name: ubuntu
    image: ubuntu:18.04
    # hostname: ubuntu
    network_mode: "host"
    volumes:
       - './home/motion-ai/:/home/motion-ai/'
       - './home/scripts/:/home/scripts/'
    restart: always
    command: ["sleep","infinity"]
```

After running ubuntu successfully, I have "startup.sh" stored in scripts folder. 

```
#!/bin/bash
cd /
apt update -qq -y
apt update
apt install -y nano sudo
apt install -qq -y make git curl jq
# cd /home/motion-ai/
cd /home/
git clone http://github.com/dcmartin/motion-ai
cd /home/motion-ai
sudo ./sh/get.motion-ai.sh
```
Once container is running, I am logging into ubuntu as "root" and running the startup script. it does what it should do, untill cloning the git for "motion-ai". Then after it complains about the sudo.
```
sudo: unable to send audit message: Unknown error -1
sudo: pam_open_session: System error
sudo: policy plugin failed session initialization
```
I also tried to run it without "sudo" but no luck.

I am not sure, if what I am trying is correct way so thought to knock community door !! Has any one tried to install motion-ai on synology ? Which way ? Even if not, what others could suggest to go forward.

Thanks.
